from datetime import datetime

# Compliance questions
compliance_date = datetime.now().strftime("%d.%m.%y")

compliance_questions = [{'question': 'Is the information in the communication fair, clear and not misleading?',
  'non_compliant_response': 'No',
  'id': 1},
 {'question': "Does the information refer to the fact that IG is regulated in a way that is promotional (for example as a benefit of opening an account or trading with IG) or suggests that the FCA has endorsed IG's products and services?",
  'non_compliant_response': 'Yes',
  'id': 2},
 {'question': 'Has the name of the relevant IG entity been included in the communication?',
  'non_compliant_response': 'No',
  'id': 3},
 {'question': 'Is the information accurate?',
  'non_compliant_response': 'No',
  'id': 4},
 {'question': 'If the information includes the benefits of a product or instrument, is there also a fair and prominent indication of any relevant risks?',
  'non_compliant_response': 'No',
  'id': 5},
 {'question': 'Is the information likely to be understood by the group it is directed to?',
  'non_compliant_response': 'No',
  'id': 6},
 {'question': 'Are any important statements or warnings disguised, diminished, or obscured?',
  'non_compliant_response': 'Yes',
  'id': 7},
 {'question': 'Is the same language used throughout?',
  'non_compliant_response': 'No',
  'id': 8},
 {'question': "Is the information up to date (today's date is) and relevant to the means of communication?",
  'non_compliant_response': 'No',
  'id': 9},
 {'question': 'Does the communication include comparative information? If so: \n    - Is any comparative information meaningful and presented in a fair and balanced way? \n    - Have the sources of the comparative information been specified? \n    - Are the key facts and assumptions used to make the comparisons included?',
  'non_compliant_response': 'No',
  'id': 10},
 {'question': 'Where the information refers to tax treatment, does it include a prominent statement that the tax treatment depends on the individual circumstances of each client and may be subject to change in the future?',
  'non_compliant_response': 'No',
  'id': 11},
 {'question': 'Does the information contain an indication of past performance of a financial instrument, a financial index, or an investment service? If so confirm: \n    - The past performance indication is not the most prominent feature of the communication. \n    - The information includes performance information covering the preceding 5 years, (or the whole period offered where less than 5 years) and the performance information is based on complete 12-month periods. \n    - The reference period and the source of information is clearly stated. \n    - The information contains a prominent warning that the figures refer to the past and that past performance is not a reliable indicator of future results. \n    - Where the indication relies on figures denominated in a currency other than pounds sterling, the currency is clearly stated, together with a warning that the return may increase or decrease because of currency fluctuations?\n    - Where the indication is based on gross performance, the effect of commissions, fees or other charges are disclosed?',
  'non_compliant_response': 'No',
  'id': 12},
 {'question': 'Where the information includes or refers to simulated past performance, is it based on actual performance of the same/substantially the same instrument (and meet the requirements in relation to past performance above) and includes a prominent warning that the figures refer to simulated past performance and that past performance is not a reliable indicator of future performance.',
  'non_compliant_response': 'No',
  'id': 13},
 {'question': 'Where the information contains information on future performance, does the information on future performance meet the requirements of COBS4.5A.14 i.e.:\n    - (a) the information is not based on or refer to simulated past performance;\n    - (b) the information is based on reasonable assumptions supported by objective data;\n    - (c) where the information is based on gross performance, the effect of commissions, fees or other charges is disclosed;\n    - (d) the information is based on performance scenarios in different market conditions (both negative and positive scenarios), and reflects the nature and risks of the specific types of instruments included in the analysis;\n    - (e) the information contains a prominent warning that such forecasts are not a reliable indicator of future performance?',
  'non_compliant_response': 'No',
  'id': 14},
 {'question': "If the FCA's name appears in the communication, the communication should not suggest FCA endorsement or approval.",
  'non_compliant_response': 'Yes',
  'id': 15},
 {'question': 'Does the communication include an invitation or inducement to engage in investment activity, such that it meets the definition of a financial promotion?',
  'non_compliant_response': 'Yes',
  'id': 16}]


cfd_questions = [{'question': 'Does the communication include the appropriate risk warning?',
  'non_compliant_response': 'No',
  'id': 1},
 {'question': 'Does the communication exclude a monetary incentive (rebates, bonuses) or non-monetary incentives to retail clients?',
  'non_compliant_response': 'No',
  'id': 2},
 {'question': 'Does the communication reference cryptoassets or cryptoasset exchange traded notes?',
  'non_compliant_response': 'Yes',
  'id': 3}]

risk_questions = [{'question': "Does the communication include 'Spread bets and CFDs are complex instruments and come with a high risk of losing money rapidly due to leverage. XX% of retail investor accounts lose money when trading spread bets and CFDs with this provider. You should consider whether you understand how spread bets and CFDs work, and whether you can afford to take the high risk of losing your money. Professional clients can lose more than they deposit. All trading involves risk. The value of shares, ETFs and ETCs bought through a share dealing account, a stocks and shares ISA or a SIPP can fall as well as rise, which could mean getting back less than you originally put in. Past performance is no guarantee of future results.'",
  'non_compliant_response': 'No',
  'id': 1},
 {'question': "\n    Does the communication include 'All trading involves risk.\n    Spread bets and CFDs are complex instruments and come with a high risk of losing money rapidly due to leverage. XX% of retail investor accounts lose money when trading Spread bets and CFDs with this provider. You should consider whether you understand how spread bets and CFDs work and whether you can afford to take the high risk of losing your money. \n    Professional clients can lose more than they deposit. \n    The value of shares, ETFs and ETCs bought through a share dealing account, a stocks and shares ISA or a SIPP can fall as well as rise, which could mean getting back less than you originally put in. Past performance is no guarantee of future results.'\n    ",
  'non_compliant_response': 'No',
  'id': 2},
 {'question': "Does the communication include 'XX% of retail CFD accounts lose money.'",
  'non_compliant_response': 'No',
  'id': 3},
 {'question': "Does the information include 'Your capital is at risk. XX% of retail CFD accounts lose money.'",
  'non_compliant_response': 'No',
  'id': 4}]
